name: Bug Report
description: Report a bug to help improve this addon.
labels: ["bug"]
body:
  - type: dropdown
    id: game-version
    attributes:
      label: Game Version (Flavor)
      options:
        - Retail
        - Mist of Pandaria - Classic
        - Burning Crusade - Classic Anniversary Edition
        - Classic
    validations:
      required: true

  - type: input
    id: addon-version
    attributes:
      label: Addon Version
      placeholder: e.g., v2.4
    validations:
      required: true

  - type: dropdown
    id: client-language
    attributes:
      label: Game Client Language
      options:
        - English (enUS / enGB)
        - German (deDE)
        - French (frFR)
        - Spanish - Spain (esES)
        - Spanish - Latin America (esMX)
        - Portuguese - Brazil (ptBR)
        - Italian (itIT)
        - Russian (ruRU)
        - Korean (koKR)
        - Chinese - Simplified (zhCN)
        - Chinese - Traditional (zhTW)
    validations:
      required: true

  - type: dropdown
    id: conflict-test
    attributes:
      label: Addon Conflict Test
      description: Does the error still occur when ALL other addons except this one are disabled?
      options:
        - "Yes, it still happens."
        - "No, it works fine without other addons."
        - "I haven't tested it yet."
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the Bug, Steps to Reproduce & Screenshots
      description: What exactly is broken, and how can we trigger the error? You can drag and drop screenshots directly into this text box.
    validations:
      required: true

  - type: textarea
    id: lua-error
    attributes:
      label: Lua Error
      description: If you received a Lua error (from the game or BugSack), paste it here.
      render: lua
    validations:
      required: false
