local addonName, Memento = ...

Memento.MEDIA_PATH = "Interface\\AddOns\\" .. addonName .. "\\media\\"

Memento.GAME_TYPE_VANILLA = (WOW_PROJECT_ID == WOW_PROJECT_CLASSIC)
Memento.GAME_TYPE_TBC = (WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC)
Memento.GAME_TYPE_CATA = (WOW_PROJECT_ID == WOW_PROJECT_CATACLYSM_CLASSIC)
---@diagnostic disable-next-line: undefined-global
Memento.GAME_TYPE_MISTS = (WOW_PROJECT_ID == WOW_PROJECT_MISTS_CLASSIC)
Memento.GAME_TYPE_MAINLINE = (WOW_PROJECT_ID == WOW_PROJECT_MAINLINE)

Memento.COLOR_NORMAL_FONT = "ffFFD200"
Memento.COLOR_WHITE_FONT = "ffFFFFFF"
Memento.COLOR_ORANGE_FONT = "ffFF8040"
Memento.COLOR_GOLD_FONT = "ffF2E699"

Memento.EVENT_ACHIEVEMENT_EARNED_PERSONAL = 1
Memento.EVENT_ACHIEVEMENT_CRITERIA_EARNED = 2
Memento.EVENT_ACHIEVEMENT_EARNED_GUILD = 3
Memento.EVENT_ENCOUNTER_END_VICTORY = 4
Memento.EVENT_ENCOUNTER_END_WIPE = 5
Memento.EVENT_DUEL_FINISHED = 6
Memento.EVENT_PVP_MATCH_COMPLETE_ARENA = 7
Memento.EVENT_PVP_MATCH_COMPLETE_BATTLEGROUND = 8
Memento.EVENT_PVP_MATCH_COMPLETE_BRAWL = 9
Memento.EVENT_PLAYER_LEVEL_UP = 10
Memento.EVENT_PLAYER_DEAD = 11
Memento.EVENT_PLAYER_LOGIN = 12
Memento.EVENT_NEW_PET = 13
Memento.EVENT_NEW_MOUNT = 14
Memento.EVENT_NEW_TOY = 15
Memento.EVENT_NEW_RECIPE = 16
Memento.EVENT_INTERVAL = 17
